In [1]:
# empty
# linspace
# aggregation function


import numpy as np

In [11]:
np.empty([2,5])

array([[1.01668834e-311, 2.32210854e-322, 0.00000000e+000,
        0.00000000e+000, 8.45593933e-307],
       [1.16095484e-028, 3.65093134e+233, 4.03555676e-144,
        2.91237123e+257, 4.71294503e+257]])

In [18]:
# linspace
np.linspace(1,4,30)

array([1.        , 1.10344828, 1.20689655, 1.31034483, 1.4137931 ,
       1.51724138, 1.62068966, 1.72413793, 1.82758621, 1.93103448,
       2.03448276, 2.13793103, 2.24137931, 2.34482759, 2.44827586,
       2.55172414, 2.65517241, 2.75862069, 2.86206897, 2.96551724,
       3.06896552, 3.17241379, 3.27586207, 3.37931034, 3.48275862,
       3.5862069 , 3.68965517, 3.79310345, 3.89655172, 4.        ])

In [19]:
# Aggregation function----->
# sum,min,max,avg/mean
np.array([[1,2,3,4],[1,7,8]])

C:\Users\Satyam\AppData\Local\Temp/ipykernel_8172/1672148711.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3,4],[1,7,8]])


array([list([1, 2, 3, 4]), list([1, 7, 8])], dtype=object)

In [56]:
x = np.array([[1,2,3,4],[1,7,8,4],[1,2,3,7]])

In [57]:
x

array([[1, 2, 3, 4],
       [1, 7, 8, 4],
       [1, 2, 3, 7]])

In [26]:
x.sum()

43

In [27]:
x.sum(axis = 0 )

array([ 3, 11, 14, 15])

In [28]:
x.sum(axis = 1)

array([10, 20, 13])

In [29]:
x

array([[1, 2, 3, 4],
       [1, 7, 8, 4],
       [1, 2, 3, 7]])

In [30]:
# max 
x.max()

8

In [31]:
# min
x.min()

1

In [32]:
x

array([[1, 2, 3, 4],
       [1, 7, 8, 4],
       [1, 2, 3, 7]])

In [36]:
# avg/mean
x.mean(axis = 1)

array([2.5 , 5.  , 3.25])

In [34]:
43/12

3.5833333333333335

In [37]:
10/4

2.5

In [38]:
x

array([[1, 2, 3, 4],
       [1, 7, 8, 4],
       [1, 2, 3, 7]])

In [47]:
# median
a = [1,2,3,9,6,45]
# 9
# odd num ----> middle value is median
# even number ----> (n+1)/2
a.sort(reverse=True)

In [49]:
a

[45, 9, 6, 3, 2, 1]

In [50]:
(a[2]+a[3])/2

4.5

In [54]:
# sort function

x

array([[1, 2, 3, 4],
       [1, 4, 7, 8],
       [1, 2, 3, 7]])

In [52]:
# ascending order
x.sort()

In [53]:
x

array([[1, 2, 3, 4],
       [1, 4, 7, 8],
       [1, 2, 3, 7]])

In [60]:
list(x)

[array([1, 2, 3, 4]), array([1, 7, 8, 4]), array([1, 2, 3, 7])]

In [62]:
# desc. order
x.sort()

In [65]:
a = [2,6,8,2]
a.sort()

In [64]:
a

[2, 2, 6, 8]

In [66]:
a

[2, 6, 8, 2]

In [67]:
a.sort(reverse=True)

In [68]:
a

[8, 6, 2, 2]

In [69]:
# argmax
# argmin
# argsort


x = np.array([[23,45,7],[56,90,8],[43,56,1]])

In [70]:
x

array([[23, 45,  7],
       [56, 90,  8],
       [43, 56,  1]])

In [72]:
x.argmax()

4

In [73]:
x.argmin()

8

In [75]:
x

array([[23, 45,  7],
       [56, 90,  8],
       [43, 56,  1]])

In [74]:
x.argsort()

array([[2, 0, 1],
       [2, 0, 1],
       [2, 0, 1]], dtype=int64)

In [76]:
x = np.array([[100,99,98]])
x.argsort()

array([[2, 1, 0]], dtype=int64)

In [77]:
# searching
x = np.array([1000,56,89,340,678,345,290])
np.where(x%2==0)

(array([0, 1, 3, 4, 6], dtype=int64),)

In [79]:
np.where(x%2!=0)

(array([2, 5], dtype=int64),)

In [83]:
# Transpose Matrix

a = np.array([[1,3,5],[6,7,9]])

In [84]:
a

array([[1, 3, 5],
       [6, 7, 9]])

In [85]:
a.T

array([[1, 6],
       [3, 7],
       [5, 9]])

In [93]:
#airthmetic operator 

#wap to add two different data
# sub,mul,div

a = np.array([[1,2,3],[3,5,7],[1,2,0]])
b = np.array([1,2,0])
c = a+b
c

array([[2, 4, 3],
       [4, 7, 7],
       [2, 4, 0]])