In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3])

In [4]:
x

array([1, 2, 3])

In [5]:
type(x)

numpy.ndarray

In [6]:
#wap to create a array of 23,45,78,1.
a = np.array([23,45,78,1])

In [7]:
a

array([23, 45, 78,  1])

In [9]:
x.shape

(3,)

In [10]:
a.shape

(4,)

In [11]:
s = np.array([[1,2,3],[4,5,6]])

In [12]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
s.shape

(2, 3)

In [39]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [40]:
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
x.shape

(1, 3, 3)

# slicing & indexing


In [17]:
a

array([23, 45, 78,  1])

In [18]:
a[2]

78

In [19]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
s[1,1]

5

In [27]:
s[2,2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [28]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
s[1,2]

6

In [35]:
s[0][2]

3

In [36]:
s[1]

array([4, 5, 6])

In [38]:
s[1][0:2]

array([4, 5])

In [72]:
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [46]:
x[0,2,1]

8

In [47]:
x.size

9

In [60]:
# function to create arrays 
# zeros
# ones

z = np.zeros([4,2])

In [61]:
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [62]:
#wap to make a array of zeros having row & col of 4,5.
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
np.zeros([0,0])

array([], shape=(0, 0), dtype=float64)

In [66]:
np.zeros([4,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [68]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [69]:
np.ones(0)

array([], dtype=float64)

In [70]:
np.ones([0,4])

array([], shape=(0, 4), dtype=float64)

In [71]:
np.ones([4,0])

array([], shape=(4, 0), dtype=float64)

In [73]:
# axis =0,1
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [76]:
x  = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [77]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
x.sum()

45

In [79]:
x.sum(axis = 0)

array([12, 15, 18])

In [80]:
x.sum(axis = 1)

array([ 6, 15, 24])

In [90]:
# arange----->
np.arange(12,230,5)

array([ 12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,  67,  72,
        77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127, 132, 137,
       142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192, 197, 202,
       207, 212, 217, 222, 227])