In [1]:
import numpy as np

In [12]:
# random + random int
np.random.randint([4,7,3])

array([2, 1, 2])

In [17]:
np.random.randint(4,size = (30,4))

array([[0, 2, 0, 1],
       [1, 1, 3, 0],
       [0, 0, 3, 2],
       [0, 2, 0, 2],
       [0, 2, 1, 2],
       [3, 1, 2, 1],
       [0, 0, 1, 2],
       [1, 2, 2, 0],
       [3, 2, 3, 1],
       [1, 0, 0, 3],
       [3, 1, 3, 0],
       [2, 3, 1, 1],
       [2, 1, 1, 0],
       [0, 0, 1, 0],
       [3, 1, 2, 0],
       [1, 3, 2, 0],
       [2, 3, 1, 2],
       [3, 1, 3, 3],
       [0, 3, 3, 1],
       [1, 2, 1, 1],
       [1, 1, 0, 1],
       [2, 1, 3, 0],
       [3, 2, 1, 2],
       [0, 2, 1, 0],
       [1, 2, 1, 1],
       [1, 2, 0, 3],
       [3, 1, 3, 0],
       [0, 2, 1, 2],
       [3, 0, 3, 0],
       [3, 2, 3, 1]])

In [19]:
np.random.randint(2,size=(2,10))

array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

In [20]:
np.random.randint(2,5,size=(2,10))

array([[3, 4, 3, 4, 2, 2, 4, 4, 4, 4],
       [2, 3, 4, 2, 4, 3, 3, 2, 4, 3]])

# Pandas

In [24]:
# how to import pandas
x = np.array([[1,2,3,4]])

In [25]:
x.shape

(1, 4)

In [26]:
# 1----> row
# 4 -----> col
# axis 0 ,1



import pandas as pd

In [34]:
x = {
    'name':['Aniket','a','b','c'],
    'age':[34,45,67,3],
    'marks':[0,1,2,3]
}

In [35]:
x

{'name': ['Aniket', 'a', 'b', 'c'],
 'age': [34, 45, 67, 3],
 'marks': [0, 1, 2, 3]}

In [36]:
type(x)

dict

In [37]:
df = pd.DataFrame(x)

In [38]:
df

name  age  marks
0  Aniket   34      0
1       a   45      1
2       b   67      2
3       c    3      3

In [42]:
df['marks'][0]=90

C:\Users\Satyam\AppData\Local\Temp/ipykernel_228/3864260052.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['marks'][0]=90


In [40]:
df.marks

0    0
1    1
2    2
3    3
Name: marks, dtype: int64

In [43]:
df

name  age  marks
0  Aniket   34     90
1       a   45      1
2       b   67      2
3       c    3      3

In [46]:
df['name'][2]='Ankit'

C:\Users\Satyam\AppData\Local\Temp/ipykernel_228/3248049126.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'][2]='Ankit'


In [47]:
df

name  age  marks
0  Aniket   34     90
1       a   45      1
2   Ankit   67      2
3       c    3      3

In [48]:
# storing the data.
# ----> use csv file to store the data.
# read the file/store the file.
file = df.to_csv('myfirstfile.csv')

In [49]:
file

In [60]:
# wap  to store df into excel file.
file = df.to_excel('mythirdfiles.xlsx',index = False)

In [59]:
file

In [62]:
df = pd.read_csv(r'C:\Users\Satyam\Downloads\train.csv')

In [63]:
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [65]:
# head
# tail
# sample

df.head(10)



Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   
5   6          50       RL         85.0    14115   Pave   NaN      IR1   
6   7          20       RL         75.0    10084   Pave   NaN      Reg   
7   8          60       RL          NaN    10382   Pave   NaN      IR1   
8   9          50       RM         51.0     6120   Pave   NaN      Reg   
9  10         190       RL         50.0     7420   Pave   NaN      Reg   

  LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
5         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
6         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
7         Lvl    AllPub  ...        0    NaN    NaN        Shed     350   
8         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
9         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  
5     10   2009        WD         Normal     143000  
6      8   2007        WD         Normal     307000  
7     11   2009        WD         Normal     200000  
8      4   2008        WD        Abnorml     129900  
9      1   2008        WD         Normal     118000  

[10 rows x 81 columns]

In [66]:
df.tail()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[5 rows x 81 columns]

In [67]:
df.tail(12)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
1448  1449          50       RL         70.0    11767   Pave   NaN      Reg   
1449  1450         180       RM         21.0     1533   Pave   NaN      Reg   
1450  1451          90       RL         60.0     9000   Pave   NaN      Reg   
1451  1452          20       RL         78.0     9262   Pave   NaN      Reg   
1452  1453         180       RM         35.0     3675   Pave   NaN      Reg   
1453  1454          20       RL         90.0    17217   Pave   NaN      Reg   
1454  1455          20       FV         62.0     7500   Pave  Pave      Reg   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
1448         Lvl    AllPub  ...        0    NaN   GdWo         NaN       0   
1449         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1450         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1451         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1452         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1453         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1454         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
1448      5   2007        WD         Normal     112000  
1449      8   2006        WD        Abnorml      92000  
1450      9   2009        WD         Normal     136000  
1451      5   2009       New        Partial     287090  
1452      5   2006        WD         Normal     145000  
1453      7   2006        WD        Abnorml      84500  
1454     10   2009        WD         Normal     185000  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[12 rows x 81 columns]

In [74]:
df.sample(3)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
640    641         120       RL         62.0    12677   Pave   NaN      IR1   
1168  1169          70       RL        120.0    13728   Pave   NaN      Reg   
908    909          20       RL          NaN     8885   Pave   NaN      IR1   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
640          Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1168         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
908          Low    AllPub  ...        0    NaN  MnPrv         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
640       4   2008        WD         Normal     274000  
1168      7   2008        WD         Normal     235000  
908       6   2006        WD         Normal     131000  

[3 rows x 81 columns]

In [77]:
# df.to_excel('files.xlsx',encoding= 'utf8' , index= False)
